# Generated by Django 5.1.6 on 2025-02-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CharacterDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Author', models.CharField(max_length=64)),
                ('CharacterDescription', models.TextField()),
                ('UniverseNumber', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UniverseDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('UniverseNumber', models.PositiveIntegerField(unique=True)),
                ('UniverseDescription', models.TextField()),
            ],
        ),
    ]
