# Generated by Django 5.1.6 on 2025-02-26 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0003_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
