# Generated by Django 5.1.6 on 2025-02-26 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0004_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_pics'),
        ),
    ]
