# Generated by Django 5.1.6 on 2025-02-26 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0006_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='default1.jpg', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, default='Visionary', max_length=64, null=True),
        ),
    ]
