# Generated by Django 5.1.6 on 2025-02-27 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0008_characterdatabase_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdatabase',
            name='UniverseNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Story_Database.universedatabase'),
        ),
    ]
