# Generated by Django 5.1.6 on 2025-02-27 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0009_alter_characterdatabase_universenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdatabase',
            name='Author',
            field=models.CharField(default='Unknown', max_length=64),
        ),
    ]
