# Generated by Django 5.1.6 on 2025-02-27 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0010_alter_characterdatabase_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterdatabase',
            name='Author',
            field=models.CharField(editable=False, max_length=64),
        ),
    ]
