# Generated by Django 5.1.6 on 2025-03-01 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Story_Database', '0011_alter_characterdatabase_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChaptersDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Author', models.CharField(editable=False, max_length=64)),
                ('Chapter', models.TextField()),
                ('UniverseNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Story_Database.universedatabase')),
            ],
        ),
        migrations.CreateModel(
            name='TalesDatabase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=64)),
                ('Author', models.CharField(editable=False, max_length=64)),
                ('Tale', models.TextField()),
                ('Character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Story_Database.characterdatabase')),
            ],
        ),
    ]
